export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
export const SET_SOURCES = "SET_SOURCES";
export const SET_SELECTED_SOURCES = "SET_SELECTED_SOURCES";
